# Generated by Django 5.0.6 on 2026-09-09 10:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tracking_id', models.CharField(editable=False, max_length=16, unique=True)),
                ('category', models.CharField(choices=[('roads', 'Roads & Potholes'), ('water', 'Water Supply'), ('garbage', 'Garbage & Sanitation'), ('power', 'Power Outages'), ('lighting', 'Street Lighting'), ('transport', 'Public Transport'), ('pollution', 'Air & Noise Pollution'), ('grievance', 'Corruption & Grievances')], max_length=20)),
                ('locality', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('progress', 'In progress'), ('resolved', 'Resolved')], default='submitted', max_length=12)),
                ('votes', models.PositiveIntegerField(default=1)),
                ('attachment_key', models.CharField(blank=True, default='', help_text='S3 object key for an uploaded photo, set after a successful presigned-URL upload.', max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'status'], name='issues_issu_categor_cf150f_idx')],
            },
        ),
    ]
